FROM bitnami/spark:3.5.0

USER root 

RUN mkdir -p /var/lib/apt/lists/partial

RUN apt-get update && apt-get install -y openjdk-17-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER 1001
